title: IDI GSoC'14
description: "A Blog for GSoC Project @IDI"

port: 3000
pygments: true

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Tejas Shah
  disqus_shortname: theCarver
  twitter: sh_tejas_sh

url : "http://tejasshah93.github.io"
